# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./card.hpp \
    ./card_pkg.hpp \
    ./card_pkg_factory.hpp \
    ./card_stack.hpp \
    ./factory_info.hpp \
    ./index2.h

#Source files
SOURCES += ./index2.cpp \
    ./main.cpp

#Forms
FORMS += ./index2.ui

#Resource file(s)
RESOURCES += ./index2.qrc
