#############################################################################
# Makefile for building: index2
# Generated by qmake (2.01a) (Qt 4.7.0) on: ? 10 27 21:24:46 2010
# Project:  nbproject\qt-Debug.pro
# Template: app
# Command: c:\Qt\2010.05\qt\bin\qmake.exe VPATH=. -o qttmp-Debug.mk nbproject\qt-Debug.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc.exe
CXX           = g++.exe
DEFINES       = -DUNICODE -DQT_LARGEFILE_SUPPORT -DQT_DLL -DQT_GUI_LIB -DQT_CORE_LIB -DQT_THREAD_SUPPORT -DQT_NEEDS_QMAIN
CFLAGS        = -g -Wall $(DEFINES)
CXXFLAGS      = -g -frtti -fexceptions -mthreads -Wall $(DEFINES)
INCPATH       = -I"c:\Qt\2010.05\qt\include\QtCore" -I"c:\Qt\2010.05\qt\include\QtGui" -I"c:\Qt\2010.05\qt\include" -I"c:\Qt\2010.05\qt\include\ActiveQt" -I"." -I"." -I"nbproject" -I"." -I"c:\Qt\2010.05\qt\mkspecs\default"
LINK        =        g++
LFLAGS        =        -enable-stdcall-fixup -Wl,-enable-auto-import -Wl,-enable-runtime-pseudo-reloc -mthreads -Wl -Wl,-subsystem,windows
LIBS        =        -L"c:\Qt\2010.05\qt\lib" -lmingw32 -lqtmaind build\Debug\MinGW_Qt-Windows\index2_resource_res.o -lQtGuid4 -lQtCored4 
QMAKE         = c:\Qt\2010.05\qt\bin\qmake.exe
IDC           = idc.exe
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = build\Debug\MinGW_Qt-Windows\index2_resource_res.o
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
DEL_FILE      = del
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
INSTALL_FILE    = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR     = $(COPY_DIR)

####### Output directory

OBJECTS_DIR   = build\Debug\MinGW_Qt-Windows

####### Files

SOURCES       = index2.cpp \
		main.cpp moc_index2.cpp
OBJECTS       = build/Debug/MinGW_Qt-Windows/index2.o \
		build/Debug/MinGW_Qt-Windows/main.o \
		build/Debug/MinGW_Qt-Windows/moc_index2.o
DIST          = 
QMAKE_TARGET  = index2
DESTDIR        = dist\Debug\MinGW_Qt-Windows\ #avoid trailing-slash linebreak
TARGET         = index2.exe
DESTDIR_TARGET = dist\Debug\MinGW_Qt-Windows\index2.exe

####### Implicit rules

.SUFFIXES: .cpp .cc .cxx .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

first: all
all: qttmp-Debug.mk  $(DESTDIR_TARGET)

$(DESTDIR_TARGET): ui_index2.h $(OBJECTS) build/Debug/MinGW_Qt-Windows/index2_resource_res.o
	$(LINK) $(LFLAGS) -o $(DESTDIR_TARGET) $(OBJECTS)  $(LIBS)


build/Debug/MinGW_Qt-Windows/index2_resource_res.o: index2_resource.rc
	windres -i index2_resource.rc -o build\Debug\MinGW_Qt-Windows\index2_resource_res.o --include-dir=. $(DEFINES)

qttmp-Debug.mk: nbproject/qt-Debug.pro  c:/Qt/2010.05/qt/mkspecs/default/qmake.conf c:/Qt/2010.05/qt/mkspecs/qconfig.pri \
		c:/Qt/2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		c:/Qt/2010.05/qt/mkspecs/features/qt_functions.prf \
		c:/Qt/2010.05/qt/mkspecs/features/qt_config.prf \
		c:/Qt/2010.05/qt/mkspecs/features/exclusive_builds.prf \
		c:/Qt/2010.05/qt/mkspecs/features/default_pre.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/default_pre.prf \
		c:/Qt/2010.05/qt/mkspecs/features/debug.prf \
		c:/Qt/2010.05/qt/mkspecs/features/default_post.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/default_post.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/rtti.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/exceptions.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/stl.prf \
		c:/Qt/2010.05/qt/mkspecs/features/shared.prf \
		c:/Qt/2010.05/qt/mkspecs/features/warn_on.prf \
		c:/Qt/2010.05/qt/mkspecs/features/qt.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/thread.prf \
		c:/Qt/2010.05/qt/mkspecs/features/moc.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/windows.prf \
		c:/Qt/2010.05/qt/mkspecs/features/resources.prf \
		c:/Qt/2010.05/qt/mkspecs/features/uic.prf \
		c:/Qt/2010.05/qt/mkspecs/features/yacc.prf \
		c:/Qt/2010.05/qt/mkspecs/features/lex.prf \
		c:/Qt/2010.05/qt/mkspecs/features/include_source_dir.prf \
		c:/Qt/2010.05/qt/lib/qtmaind.prl
	$(QMAKE) VPATH=. -o qttmp-Debug.mk nbproject\qt-Debug.pro
c:\Qt\2010.05\qt\mkspecs\qconfig.pri:
c:\Qt\2010.05\qt\mkspecs\modules\qt_webkit_version.pri:
c:\Qt\2010.05\qt\mkspecs\features\qt_functions.prf:
c:\Qt\2010.05\qt\mkspecs\features\qt_config.prf:
c:\Qt\2010.05\qt\mkspecs\features\exclusive_builds.prf:
c:\Qt\2010.05\qt\mkspecs\features\default_pre.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\default_pre.prf:
c:\Qt\2010.05\qt\mkspecs\features\debug.prf:
c:\Qt\2010.05\qt\mkspecs\features\default_post.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\default_post.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\rtti.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\exceptions.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\stl.prf:
c:\Qt\2010.05\qt\mkspecs\features\shared.prf:
c:\Qt\2010.05\qt\mkspecs\features\warn_on.prf:
c:\Qt\2010.05\qt\mkspecs\features\qt.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\thread.prf:
c:\Qt\2010.05\qt\mkspecs\features\moc.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\windows.prf:
c:\Qt\2010.05\qt\mkspecs\features\resources.prf:
c:\Qt\2010.05\qt\mkspecs\features\uic.prf:
c:\Qt\2010.05\qt\mkspecs\features\yacc.prf:
c:\Qt\2010.05\qt\mkspecs\features\lex.prf:
c:\Qt\2010.05\qt\mkspecs\features\include_source_dir.prf:
c:\Qt\2010.05\qt\lib\qtmaind.prl:
qmake:  FORCE
	@$(QMAKE) VPATH=. -o qttmp-Debug.mk nbproject\qt-Debug.pro

dist:
	$(ZIP) index2.zip $(SOURCES) $(DIST) nbproject\nbproject\qt-Debug.pro c:\Qt\2010.05\qt\mkspecs\qconfig.pri c:\Qt\2010.05\qt\mkspecs\modules\qt_webkit_version.pri c:\Qt\2010.05\qt\mkspecs\features\qt_functions.prf c:\Qt\2010.05\qt\mkspecs\features\qt_config.prf c:\Qt\2010.05\qt\mkspecs\features\exclusive_builds.prf c:\Qt\2010.05\qt\mkspecs\features\default_pre.prf c:\Qt\2010.05\qt\mkspecs\features\win32\default_pre.prf c:\Qt\2010.05\qt\mkspecs\features\debug.prf c:\Qt\2010.05\qt\mkspecs\features\default_post.prf c:\Qt\2010.05\qt\mkspecs\features\win32\default_post.prf c:\Qt\2010.05\qt\mkspecs\features\win32\rtti.prf c:\Qt\2010.05\qt\mkspecs\features\win32\exceptions.prf c:\Qt\2010.05\qt\mkspecs\features\win32\stl.prf c:\Qt\2010.05\qt\mkspecs\features\shared.prf c:\Qt\2010.05\qt\mkspecs\features\warn_on.prf c:\Qt\2010.05\qt\mkspecs\features\qt.prf c:\Qt\2010.05\qt\mkspecs\features\win32\thread.prf c:\Qt\2010.05\qt\mkspecs\features\moc.prf c:\Qt\2010.05\qt\mkspecs\features\win32\windows.prf c:\Qt\2010.05\qt\mkspecs\features\resources.prf c:\Qt\2010.05\qt\mkspecs\features\uic.prf c:\Qt\2010.05\qt\mkspecs\features\yacc.prf c:\Qt\2010.05\qt\mkspecs\features\lex.prf c:\Qt\2010.05\qt\mkspecs\features\include_source_dir.prf c:\Qt\2010.05\qt\lib\qtmaind.prl  HEADERS RESOURCES IMAGES SOURCES OBJECTIVE_SOURCES FORMS YACCSOURCES YACCSOURCES LEXSOURCES 

clean: compiler_clean 
	-$(DEL_FILE) build\Debug\MinGW_Qt-Windows\index2.o build\Debug\MinGW_Qt-Windows\main.o build\Debug\MinGW_Qt-Windows\moc_index2.o
	-$(DEL_FILE) build\Debug\MinGW_Qt-Windows\index2_resource_res.o

distclean: clean
	-$(DEL_FILE) $(DESTDIR_TARGET)
	-$(DEL_FILE) qttmp-Debug.mk

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_index2.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_index2.cpp
moc_index2.cpp: ui_index2.h \
		card_stack.hpp \
		card.hpp \
		card_pkg.hpp \
		factory_info.hpp \
		card_pkg_factory.hpp \
		index2.h
	moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 index2.h -o moc_index2.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_index2.h
compiler_uic_clean:
	-$(DEL_FILE) ui_index2.h
ui_index2.h: index2.ui
	uic.exe index2.ui -o ui_index2.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 



####### Compile

build/Debug/MinGW_Qt-Windows/index2.o: index2.cpp index2.h \
		ui_index2.h \
		card_stack.hpp \
		card.hpp \
		card_pkg.hpp \
		factory_info.hpp \
		card_pkg_factory.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\Debug\MinGW_Qt-Windows\index2.o index2.cpp

build/Debug/MinGW_Qt-Windows/main.o: main.cpp index2.h \
		ui_index2.h \
		card_stack.hpp \
		card.hpp \
		card_pkg.hpp \
		factory_info.hpp \
		card_pkg_factory.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\Debug\MinGW_Qt-Windows\main.o main.cpp

build/Debug/MinGW_Qt-Windows/moc_index2.o: moc_index2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\Debug\MinGW_Qt-Windows\moc_index2.o moc_index2.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

